
services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Monta el script en la carpeta de inicialización

  app:
    image: turnosbackend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://sql-server:1433;databaseName=turnos;encrypt=false
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=YourStrong@Passw0rd
    ports:
      - "8080"
    depends_on:
      - sql-server

volumes:
  sql_data:  # Este volumen se usará para el servicio de SQL Server
